### ISSUE TITLE
Dependencies are not listed on Curseforge page

### ISSUE THREAD

**Issue by Lord-Memester** [IDarKay/Features-mod#2]
https://www.curseforge.com/minecraft/mc-mods/features-mod#dependence links to the description.

**Comment by IDarKay** [comment]
I know but i don't know how to add that

**Comment by alice-dops** [comment]
It's donne

**Comment by Lord-Memester** [comment]
not fixed, reopen

**Comment by Lord-Memester** [comment]
should link to [here](https://www.curseforge.com/minecraft/mc-mods/features-mod/relations/dependencies)

**Comment by alice-dops** [comment]
![image](https://user-images.githubusercontent.com/45518780/96368391-f082e500-1153-11eb-8d3e-bb993dda102c.png)
 
It's fix

**Comment by alice-dops** [comment]
oh i see wath ou want but IDK how do that

**Comment by Lord-Memester** [comment]
just edit the readme.md file on the git, I think.
replace https://www.curseforge.com/minecraft/mc-mods/features-mod#dependence with https://www.curseforge.com/minecraft/mc-mods/features-mod/relations/dependencies
